# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Tesis Monitoreo Acústico y Analisis de Sonidos Naturales
author: Josè Aillapi
logo: logo.png
copyright: "2025" # Copyright year to be displayed in the book footer

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  allow_errors: true
  
parse:
  myst_enable_extensions: 
    - colon_fence
    - dollarmath
    - html_image
    - linkify
    - substitution
  

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib
  
sphinx:
  extra_extensions: [bokeh.sphinxext.bokeh_plot]
  config:
    language: es
    bibtex_reference_style: author_year

